title: "ToolEsy"
description: "Use ToolEsy’s 100+ free web tools for text editing, file conversion, calculators and generators. Fast, secure and easy. No account needed."
baseurl: "" 
url: "https://www.toolesy.com"

# SEO settings
lang: "en"
timezone: "Asia/Kolkata"

# Social Links (update if needed)
social:
  facebook: "https://www.facebook.com/toolesychat"
  linkedin: "https://www.linkedin.com/company/toolesy/"


# Favicon and logo (update if needed)
logo: "https://www.toolesy.com/toolesy-logo.png"
favicon: "/assets/images/favicon.ico"

# Build Settings
markdown: kramdown
theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sitemap enable
defaults:
  -
    scope:
      path: ""
    values:
      sitemap: true

# Exclude unnecessary system/work files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
